App.Product = DS.Model.extend(
    {
        title: DS.attr('string'),
        price: DS.attr('number'),
        description: DS.attr('string'),
        isOnSale: DS.attr('boolean'),
        image: DS.attr('string'),
        reviews: DS.hasMany('review', { async: true }),
        crafter: DS.belongsTo('contact', { async: true })
    }
);

App.Product.FIXTURES = [
    {  id: 1,
        title: 'Flint',
        price: 99,
        description: 'Flint is a hard, sedimentary cryptocrystalline form of the mineral quartz, categorized as a variety of chert.',
        isOnSale: true,
        image: 'images/products/flint.png',
        reviews: [100, 101],
        crafter: 200,
        ratings: [2, 1, 3, 3]
    },
    {
        id: 2,
        title: 'Kindling',
        price: 249,
        description: 'Easily combustible small sticks or twigs used for starting a fire.',
        isOnSale: false,
        image: 'images/products/kindling.png',
        reviews: [],
        crafter: 201,
        ratings: [2, 1, 3, 3]
    },
    {
        id: 3,
        title: 'Matches',
        price: 499,
        description: 'One end is coated with a material that can be ignited by frictional heat generated by striking the match against a suitable surface.',
        isOnSale: true,
        reviews: [],
        image: 'images/products/matches.png',
        crafter: 201,
        ratings: [2, 1, 3, 3]
    },
    {
        id: 4,
        title: 'Bow Drill',
        price: 999,
        description: 'The bow drill is an ancient tool. While it was usually used to make fire, it was also used for primitive woodworking and dentistry.',
        isOnSale: false,
        reviews: [],
        image: 'images/products/bow-drill.png',
        crafter: 200,
        ratings: [1, 3, 3]
    },
    {
        id: 5,
        title: 'Tinder',
        price: 499,
        description: 'Tinder is easily combustible material used to ignite fires by rudimentary methods.',
        isOnSale: true,
        reviews: [],
        image: 'images/products/tinder.png',
        crafter: 201,
        ratings: [2, 1, 3]
    },
    {
        id: 6,
        title: 'Birch Bark Shaving',
        price: 999,
        description: 'Fresh and easily combustable',
        isOnSale: true,
        reviews: [],
        image: 'images/products/birch.png',
        crafter: 201,
        ratings: [2, 3, 5]
    }
];

App.ProductRoute = Ember.Route.extend(
    {
        model: function(routeParams)
        {
            console.log(routeParams.title);
            return  this.store.find('product', routeParams.product_id);
        }
    }
);

App.ProductsRoute = Ember.Route.extend(
    {
        model: function()
        {
            return this.store.find('product', { order: 'title' });
        }
    }
);
App.ProductsController = Ember.ArrayController.extend(
    {
        sortProperties: ['title']
    }
);

App.Review = DS.Model.extend(
    {
        text: DS.attr('string'),
        reviewedAt: DS.attr('number'),
        product: DS.belongsTo('product')
    }
);
App.Review.FIXTURES = [
    { id: 100, product: 1, text: "Started a fire in no time!"},
    { id: 101, product: 1, text: "Not the brightest flame, but warm!"}
];

